/**
 * عنوان الـ API الأساسي — يُعرَّف في .env كـ VITE_API_BASE_URL
 * مثال: http://localhost:8000/api
 */
export const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL?.replace(/\/$/, '') || '/api';

/** مسارات تطبيق المتاجر — Route::prefix('v1/auth') */
export const STORE_AUTH_ENDPOINTS = {
  login: '/v1/auth/store/login',
  verifyJoin: '/v1/auth/store/verify-join',
  logout: '/v1/auth/logout',
  passwordForgot: '/v1/auth/password/forgot',
  passwordVerifyOtp: '/v1/auth/password/verify-otp',
  passwordReset: '/v1/auth/password/reset',
};

export const API_ENDPOINTS = {
  // GET /api/user — المستخدم المسجّل (auth:sanctum)
  currentUser: '/user',
  // POST /api/stores/join — تقديم طلب انضمام وإرسال رمز OTP لإيميل المتجر
  storesJoin: '/stores/join',
  // GET /api/zones — قائمة المناطق
  zones: '/zones',
  storeLogin: STORE_AUTH_ENDPOINTS.login,
  storeVerifyJoin: STORE_AUTH_ENDPOINTS.verifyJoin,
  logout: STORE_AUTH_ENDPOINTS.logout,
  plans: '/plans',
  campaigns: '/campaigns',
  campaign: (id) => `/campaigns/${id}`,
  catalogCategories: '/catalog/categories',
  catalogAttributes: '/catalog/attributes',
  myStoreProducts: '/my-store/products',
  myStoreProfile: '/my-store',
  myStoreProduct: (id) => `/my-store/products/${id}`,
  myStoreProductVariants: (productId) => `/my-store/products/${productId}/variants`,
  myStoreProductArchive: (id) => `/my-store/products/${id}/archive`,
  myStoreProductRestore: (id) => `/my-store/products/${id}/restore`,
  product: (id) => `/products/${id}`,
  storeSubscribe: '/stores/subscribe',
  storeSubscribePreview: '/stores/subscribe/preview',
  storePlanRenew: (storeId) => `/stores/${storeId}/renew`,
  storePlanChange: (storeId, planId) => `/stores/${storeId}/change-plan/${planId}`,
  storePlanSubscriptions: (storeId) => `/stores/${storeId}/subscriptions`,
  storeShow: (storeId) => `/stores/${storeId}`,
  storeCampaignSubscribe: (storeId) => `/stores/${storeId}/campaigns/subscribe`,
  storeWalletCharge: '/stores/wallet/charge',
  storeWalletWithdraw: '/stores/wallet/withdraw',
  walletBalance: '/wallet/balance',
  walletLogs: '/wallet/logs',
  custodySummary: '/stores/custody/summary',
  custodyLogs: '/stores/custody/logs',
  storeDashboard: '/stores/dashboard',
  storeDashboardTotalNewOrders: '/stores/dashboard/total-new-orders',
  storeDashboardTotalEmployees: '/stores/dashboard/total-employees',
  storeRatings: (storeId) => `/stores/${storeId}/ratings`,
  inventory: '/inventory',
  inventoryShipments: '/inventory/shipments',
  inventoryShipment: (id) => `/inventory/shipments/${id}`,
  inventoryVariant: (variantId) => `/inventory/variants/${variantId}`,
  inventoryVariantMovements: (variantId) => `/inventory/variants/${variantId}/movements`,
  inventoryAdjust: '/inventory/adjust',
  financeRevenueOverview: '/finance/revenue-overview',
  financeProfitOverview: '/finance/profit-overview',
  financeTransactions: '/finance/transactions',
  financeTransaction: (id) => `/finance/transactions/${id}`,
  financeAccountStatement: '/finance/account-statement',
  financeExport: '/finance/export',
  promotions: '/promotions',
  promotion: (id) => `/promotions/${id}`,
  promotionToggle: (id) => `/promotions/${id}/toggle`,
  posInit: '/pos/init',
  posCatalog: '/pos/catalog',
  posCart: '/pos/cart',
  posCartItem: (itemId) => `/pos/cart/${itemId}`,
  posCheckout: '/pos/checkout',
  posRefund: '/pos/refund',
  posExchange: '/pos/exchange',
  orders: '/orders',
  order: (id) => `/orders/${id}`,
  orderStatus: (id) => `/orders/${id}/status`,
  orderCancel: (id) => `/orders/${id}/cancel`,
  orderPrepare: (id) => `/orders/${id}/prepare`,
  orderConfirmDelivery: (id) => `/orders/${id}/confirm-delivery`,
  ordersChat: '/orders/chat',
  ordersChatStore: '/orders/chat/store',
  ordersChatMessages: (id) => `/orders/chat/${id}/messages`,
  updateStore: (storeId) => `/admin/stores/${storeId}`,
  employees: '/employees',
  employee: (id) => `/employees/${id}`,
  employeeToggle: (id) => `/employees/${id}/toggle`,
  notifications: '/notifications',
  notificationsReadAll: '/notifications/read-all',
  notificationRead: (id) => `/notifications/${id}/read`,
  notificationTrigger: '/notifications/trigger',
};
